### ISSUE TITLE
Seems not to be loading all the values

### ISSUE THREAD

**Issue by Cannonb4ll** [MikeZange/laravel-database-translations#3]
I am not sure if its unfinished work, but I tried using your package but it seems its not loading all the translations.

For example, I have done 2 commands to load 2 languages in, NL and EN, and this is the result:

![example](http://screenshot.serverbuilds.nl/321j3G2P0i2T/Image%202017-05-17%20at%203.20.44%20PM.png)

The validation exists in EN files but its not beeing loaded in as you can see. Am I doing something wrong?

**Comment by mikezange** [comment]
Apologies, I didn't get notified of this issue being opened.

You have probably moved on by now but did you have your language files in:
`resources/lang/en/validation.php` and `resources/lang/nl/validation.php`?

I will investigate anyway just in case.

**Comment by Cannonb4ll** [comment]
Thank you for your reply! :)

I have not been able to fix this sadly enough, though, I still need this very badly. My language files where indeed in those location. There were 3 languages in total for validation present, EN FR and NL.
